# Generated by Django 3.2.3 on 2021-05-29 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210529_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='answers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.answers'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.questions'),
        ),
    ]
