# Generated by Django 3.2.3 on 2021-05-29 16:31

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210529_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='manager',
            field=models.CharField(default=django.contrib.auth.models.AbstractUser.get_full_name, max_length=250, verbose_name='Руководитель'),
        ),
    ]
