# Generated by Django 3.2.3 on 2021-05-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_projects_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='manager',
            field=models.CharField(blank=True, max_length=250, verbose_name='Руководитель'),
        ),
    ]
