# Generated by Django 3.2.3 on 2021-05-30 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_rename_projects_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='projectId',
        ),
        migrations.RemoveField(
            model_name='project',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='project',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='projectId',
        ),
        migrations.AddField(
            model_name='answers',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='questions',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
