# Generated by Django 3.2.3 on 2021-05-30 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_project_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='count',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='questions',
        ),
        migrations.AddField(
            model_name='answers',
            name='comment1',
            field=models.TextField(null=True, verbose_name='Комментарий к вопросу 1'),
        ),
        migrations.AddField(
            model_name='answers',
            name='comment10',
            field=models.TextField(null=True, verbose_name='Комментарий к вопросу 10'),
        ),
        migrations.AddField(
            model_name='answers',
            name='comment2',
            field=models.TextField(null=True, verbose_name='Комментарий к вопросу 2'),
        ),
        migrations.AddField(
            model_name='answers',
            name='comment3',
            field=models.TextField(null=True, verbose_name='Комментарий к вопросу 3'),
        ),
        migrations.AddField(
            model_name='answers',
            name='comment4',
            field=models.TextField(null=True, verbose_name='Комментарий к вопросу 4'),
        ),
        migrations.AddField(
            model_name='answers',
            name='comment5',
            field=models.TextField(null=True, verbose_name='Комментарий к вопросу 5'),
        ),
        migrations.AddField(
            model_name='answers',
            name='comment6',
            field=models.TextField(null=True, verbose_name='Комментарий к вопросу 6'),
        ),
        migrations.AddField(
            model_name='answers',
            name='comment7',
            field=models.TextField(null=True, verbose_name='Комментарий к вопросу 7'),
        ),
        migrations.AddField(
            model_name='answers',
            name='comment8',
            field=models.TextField(null=True, verbose_name='Комментарий к вопросу 8'),
        ),
        migrations.AddField(
            model_name='answers',
            name='comment9',
            field=models.TextField(null=True, verbose_name='Комментарий к вопросу 9'),
        ),
        migrations.AddField(
            model_name='answers',
            name='questions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.questions'),
        ),
        migrations.AddField(
            model_name='answers',
            name='rating1',
            field=models.IntegerField(default=0, verbose_name='Оценка вопроса 1'),
        ),
        migrations.AddField(
            model_name='answers',
            name='rating10',
            field=models.IntegerField(null=True, verbose_name='Оценка вопроса 10'),
        ),
        migrations.AddField(
            model_name='answers',
            name='rating2',
            field=models.IntegerField(default=0, null=True, verbose_name='Оценка вопроса 2'),
        ),
        migrations.AddField(
            model_name='answers',
            name='rating3',
            field=models.IntegerField(null=True, verbose_name='Оценка вопроса 3'),
        ),
        migrations.AddField(
            model_name='answers',
            name='rating4',
            field=models.IntegerField(null=True, verbose_name='Оценка вопроса 4'),
        ),
        migrations.AddField(
            model_name='answers',
            name='rating5',
            field=models.IntegerField(null=True, verbose_name='Оценка вопроса 5'),
        ),
        migrations.AddField(
            model_name='answers',
            name='rating6',
            field=models.IntegerField(null=True, verbose_name='Оценка вопроса 6'),
        ),
        migrations.AddField(
            model_name='answers',
            name='rating7',
            field=models.IntegerField(null=True, verbose_name='Оценка вопроса 7'),
        ),
        migrations.AddField(
            model_name='answers',
            name='rating8',
            field=models.IntegerField(null=True, verbose_name='Оценка вопроса 8'),
        ),
        migrations.AddField(
            model_name='answers',
            name='rating9',
            field=models.IntegerField(null=True, verbose_name='Оценка вопроса 9'),
        ),
        migrations.AddField(
            model_name='questions',
            name='question1',
            field=models.TextField(default=0, verbose_name='Вопрос 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='question10',
            field=models.TextField(null=True, verbose_name='Вопрос 10'),
        ),
        migrations.AddField(
            model_name='questions',
            name='question2',
            field=models.TextField(null=True, verbose_name='Вопрос 2'),
        ),
        migrations.AddField(
            model_name='questions',
            name='question3',
            field=models.TextField(null=True, verbose_name='Вопрос 3'),
        ),
        migrations.AddField(
            model_name='questions',
            name='question4',
            field=models.TextField(null=True, verbose_name='Вопрос 4'),
        ),
        migrations.AddField(
            model_name='questions',
            name='question5',
            field=models.TextField(null=True, verbose_name='Вопрос 5'),
        ),
        migrations.AddField(
            model_name='questions',
            name='question6',
            field=models.TextField(null=True, verbose_name='Вопрос 6'),
        ),
        migrations.AddField(
            model_name='questions',
            name='question7',
            field=models.TextField(null=True, verbose_name='Вопрос 7'),
        ),
        migrations.AddField(
            model_name='questions',
            name='question8',
            field=models.TextField(null=True, verbose_name='Вопрос 8'),
        ),
        migrations.AddField(
            model_name='questions',
            name='question9',
            field=models.TextField(null=True, verbose_name='Вопрос 9'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
