# Generated by Django 3.2.3 on 2021-05-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20210530_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='comment1',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к вопросу 1'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='comment10',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к вопросу 10'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='comment2',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к вопросу 2'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='comment3',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к вопросу 3'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='comment4',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к вопросу 4'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='comment5',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к вопросу 5'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='comment6',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к вопросу 6'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='comment7',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к вопросу 7'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='comment8',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к вопросу 8'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='comment9',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к вопросу 9'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='rating10',
            field=models.IntegerField(default=0, null=True, verbose_name='Оценка вопроса 10'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='rating3',
            field=models.IntegerField(default=0, null=True, verbose_name='Оценка вопроса 3'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='rating4',
            field=models.IntegerField(default=0, null=True, verbose_name='Оценка вопроса 4'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='rating5',
            field=models.IntegerField(default=0, null=True, verbose_name='Оценка вопроса 5'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='rating6',
            field=models.IntegerField(default=0, null=True, verbose_name='Оценка вопроса 6'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='rating7',
            field=models.IntegerField(default=0, null=True, verbose_name='Оценка вопроса 7'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='rating8',
            field=models.IntegerField(default=0, null=True, verbose_name='Оценка вопроса 8'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='rating9',
            field=models.IntegerField(default=0, null=True, verbose_name='Оценка вопроса 9'),
        ),
    ]
