# Generated by Django 3.2.3 on 2021-05-30 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20210530_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='questions',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
