# Generated by Django 3.2.3 on 2021-05-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20210530_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Название'),
        ),
    ]
