# Generated by Django 3.2.3 on 2021-06-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_questions_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
