# Generated by Django 3.2.3 on 2021-06-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20210601_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.RemoveField(
            model_name='questions',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question10',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question6',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question7',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question8',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question9',
        ),
    ]
