# Generated by Django 3.2.3 on 2021-06-01 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_questions_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
