# Generated by Django 3.2.3 on 2021-06-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_question_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='iter',
            field=models.IntegerField(default=1, null=True, verbose_name='Номер итерации'),
        ),
    ]
