# Generated by Django 3.2.3 on 2021-06-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_question_iter'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionIterTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.ManyToManyField(to='projects.Question')),
            ],
            options={
                'verbose_name': 'Вопрос итерации 2',
                'verbose_name_plural': 'Вопросы итерации 2',
            },
        ),
    ]
