# Generated by Django 3.2.3 on 2021-06-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_questionitertwo'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionitertwo',
            name='title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Название опроса'),
        ),
    ]
