# Generated by Django 3.2.3 on 2021-06-02 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_questionitertwo_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='comment10',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='comment6',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='comment7',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='comment8',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='comment9',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='rating1',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='rating10',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='rating2',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='rating3',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='rating4',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='rating5',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='rating6',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='rating7',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='rating8',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='rating9',
        ),
        migrations.AlterField(
            model_name='answers',
            name='questions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.questionitertwo'),
        ),
    ]
