# Generated by Django 3.2.3 on 2021-06-02 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_answers_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionitertwo',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
