# Generated by Django 3.2.3 on 2021-06-02 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0030_questionitertwo_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Название опроса')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'verbose_name': 'Итоговый вопрос',
                'verbose_name_plural': 'Итоговые вопросы',
            },
        ),
        migrations.CreateModel(
            name='FinalAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к вопросу 1')),
                ('expert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.finalquestion')),
            ],
            options={
                'verbose_name': 'Итоговый ответ',
                'verbose_name_plural': 'Итоговые ответы',
            },
        ),
    ]
